# Generated by Django 5.0.2 on 2024-02-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nom_application', '0005_itinerary_arrival_time_itinerary_departure_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='departure_location',
            field=models.CharField(max_length=255),
        ),
    ]
