# Generated by Django 5.0.2 on 2024-02-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nom_application', '0007_itinerary_number_of_seats_itinerary_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='transport_type',
            field=models.CharField(choices=[('bus', 'Bus'), ('train', 'Train'), ('avion', 'Avion')], default='train', max_length=10),
        ),
    ]
