# Generated by Django 5.0.2 on 2024-02-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nom_application', '0008_itinerary_transport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='transport_type',
            field=models.CharField(choices=[('voiture', 'Voiture'), ('train', 'Train'), ('avion', 'Avion')], default='train', max_length=10),
        ),
    ]
