# Generated by Django 5.0.2 on 2024-02-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nom_application', '0010_remove_reservation_voyage_reservation_itinerary'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
    ]
