# Generated by Django 5.0.2 on 2024-02-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nom_application', '0011_yourreservationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourReservationModel',
        ),
    ]
